_target_: concdvae.pl_modules.decoder.GemNetTDecoder             # Decoder based on GemNet-T
hidden_dim: 128                                                  # Atom/edge embedding size inside GemNet-T
latent_dim: ${model.latent_dim}                                  # Latent z dimension
time_emb_dim: ${model.time_emb_dim}                              # Time embedding dimension (z concatenation)
max_neighbors: ${model.max_neighbors}                            # Max neighbors per atom (OTF graph)
radius: ${model.radius}                                          # Cutoff radius (Å) for neighbor search
scale_file: ${oc.env:PROJECT_ROOT}/concdvae/pl_modules/gemnet/gemnet-dT.json  # Precomputed GemNet scaling
